insert into products (name, price, stock) values ('Turkey Leg With Drum And Thigh', 10.94, 951);
insert into products (name, price, stock) values ('Shiro Miso', 10.16, 931);
insert into products (name, price, stock) values ('Crawfish', 2.94, 657);
insert into products (name, price, stock) values ('Shrimp - Baby, Cold Water', 4.38, 708);
insert into products (name, price, stock) values ('Wasabi Powder', 17.96, 782);
insert into products (name, price, stock) values ('Apple - Northern Spy', 15.75, 891);
insert into products (name, price, stock) values ('Pepper - Green Thai', 11.92, 835);
insert into products (name, price, stock) values ('Bananas', 12.26, 869);
insert into products (name, price, stock) values ('Foil Cont Round', 2.1, 903);
insert into products (name, price, stock) values ('Sauce - Mint', 10.13, 607);
insert into products (name, price, stock) values ('Cilantro / Coriander - Fresh', 8.34, 752);
insert into products (name, price, stock) values ('Bread - Mini Hamburger Bun', 2.45, 999);
insert into products (name, price, stock) values ('Wine - Zonnebloem Pinotage', 10.3, 621);
insert into products (name, price, stock) values ('Grapes - Black', 13.34, 603);
insert into products (name, price, stock) values ('Wine - Magnotta - Cab Franc', 11.46, 588);
insert into products (name, price, stock) values ('Vodka - Lemon, Absolut', 1.71, 761);
insert into products (name, price, stock) values ('Kellogs Cereal In A Cup', 13.05, 767);
insert into products (name, price, stock) values ('Ice Cream Bar - Oreo Cone', 18.08, 943);
insert into products (name, price, stock) values ('Wine - Magnotta, Merlot Sr Vqa', 12.99, 544);
insert into products (name, price, stock) values ('Molasses - Fancy', 8.09, 726);
insert into products (name, price, stock) values ('Wine - Clavet Saint Emilion', 14.67, 811);
insert into products (name, price, stock) values ('Beans - Butter Lrg Lima', 16.37, 602);
insert into products (name, price, stock) values ('Wine - Red, Pinot Noir, Chateau', 5.92, 683);
insert into products (name, price, stock) values ('Quinoa', 12.69, 503);
insert into products (name, price, stock) values ('Beets - Golden', 3.06, 569);
insert into products (name, price, stock) values ('Flour - Chickpea', 9.32, 956);
insert into products (name, price, stock) values ('Samosa - Veg', 4.11, 992);
insert into products (name, price, stock) values ('Chicken - Leg / Back Attach', 2.52, 993);
insert into products (name, price, stock) values ('Fondant - Icing', 16.64, 865);
insert into products (name, price, stock) values ('Tomatoes Tear Drop', 13.25, 562);
insert into products (name, price, stock) values ('Energy Drink - Franks Pineapple', 17.04, 904);
insert into products (name, price, stock) values ('Chip - Potato Dill Pickle', 10.36, 561);
insert into products (name, price, stock) values ('Lamb - Whole Head Off', 19.4, 648);
insert into products (name, price, stock) values ('Bread Roll Foccacia', 14.03, 683);
insert into products (name, price, stock) values ('Soup - Campbells, Lentil', 3.6, 697);
insert into products (name, price, stock) values ('Creme De Menth - White', 13.32, 799);
insert into products (name, price, stock) values ('Sage - Fresh', 16.17, 551);
insert into products (name, price, stock) values ('Juice - Mango', 9.3, 755);
insert into products (name, price, stock) values ('Contreau', 2.35, 598);
insert into products (name, price, stock) values ('Muffin Mix - Blueberry', 1.54, 668);
insert into products (name, price, stock) values ('Mayonnaise', 14.13, 527);
insert into products (name, price, stock) values ('Beef - Tender Tips', 7.45, 526);
insert into products (name, price, stock) values ('Nutmeg - Ground', 16.92, 902);
insert into products (name, price, stock) values ('Fib N9 - Prague Powder', 11.12, 594);
insert into products (name, price, stock) values ('Oil - Olive Bertolli', 12.8, 702);
insert into products (name, price, stock) values ('Pork - Tenderloin, Frozen', 10.83, 942);
insert into products (name, price, stock) values ('Pear - Halves', 15.07, 677);
insert into products (name, price, stock) values ('Bread - Dark Rye, Loaf', 3.25, 985);
insert into products (name, price, stock) values ('Turkey - Whole, Fresh', 14.62, 613);
insert into products (name, price, stock) values ('Salt - Table', 16.03, 901);
insert into products (name, price, stock) values ('Tomato - Plum With Basil', 14.24, 805);
insert into products (name, price, stock) values ('Oil - Truffle, White', 13.18, 679);
insert into products (name, price, stock) values ('Apple - Royal Gala', 6.8, 627);
insert into products (name, price, stock) values ('Pan Grease', 6.96, 929);
insert into products (name, price, stock) values ('Bread - 10 Grain Parisian', 10.28, 896);
insert into products (name, price, stock) values ('Wine - Rosso Toscano Igt', 7.9, 605);
insert into products (name, price, stock) values ('Macaroons - Two Bite Choc', 5.27, 964);
insert into products (name, price, stock) values ('Cheese - Brie, Cups 125g', 14.54, 642);
insert into products (name, price, stock) values ('Bar Special K', 9.64, 805);
insert into products (name, price, stock) values ('The Pop Shoppe Pinapple', 17.94, 787);
insert into products (name, price, stock) values ('Trout - Hot Smkd, Dbl Fillet', 4.22, 945);
insert into products (name, price, stock) values ('Seedlings - Clamshell', 1.19, 793);
insert into products (name, price, stock) values ('Soup Bowl Clear 8oz92008', 2.95, 897);
insert into products (name, price, stock) values ('Papayas', 9.35, 827);
insert into products (name, price, stock) values ('Wine - Toasted Head', 14.48, 706);
insert into products (name, price, stock) values ('Tea - Apple Green Tea', 18.11, 838);
insert into products (name, price, stock) values ('Marzipan 50/50', 1.48, 874);
insert into products (name, price, stock) values ('Snails - Large Canned', 8.03, 503);
insert into products (name, price, stock) values ('Shallots', 12.92, 769);
insert into products (name, price, stock) values ('Table Cloth 62x114 Colour', 7.54, 504);
insert into products (name, price, stock) values ('White Fish - Filets', 6.22, 753);
insert into products (name, price, stock) values ('Kale - Red', 18.07, 833);
insert into products (name, price, stock) values ('Wine - Clavet Saint Emilion', 3.07, 631);
insert into products (name, price, stock) values ('Turnip - White, Organic', 13.77, 939);
insert into products (name, price, stock) values ('Tea - Jasmin Green', 14.43, 970);
insert into products (name, price, stock) values ('Soup Campbells - Italian Wedding', 2.1, 525);
insert into products (name, price, stock) values ('Cakes Assorted', 1.98, 759);
insert into products (name, price, stock) values ('Seaweed Green Sheets', 19.41, 983);
insert into products (name, price, stock) values ('Salad Dressing', 9.96, 521);
insert into products (name, price, stock) values ('Wine - Magnotta, Merlot Sr Vqa', 11.26, 787);
insert into products (name, price, stock) values ('Nantucket Orange Juice', 1.82, 732);
insert into products (name, price, stock) values ('Arizona - Green Tea', 8.38, 810);
insert into products (name, price, stock) values ('Sage - Rubbed', 12.86, 811);
insert into products (name, price, stock) values ('Halibut - Whole, Fresh', 14.48, 697);
insert into products (name, price, stock) values ('Potatoes - Idaho 100 Count', 14.12, 890);
insert into products (name, price, stock) values ('Salmon - Atlantic, No Skin', 9.93, 944);
insert into products (name, price, stock) values ('Cakes Assorted', 4.32, 530);
insert into products (name, price, stock) values ('Water - Spring 1.5lit', 14.14, 855);
insert into products (name, price, stock) values ('Beef - Tenderloin Tails', 10.57, 556);
insert into products (name, price, stock) values ('Mousse - Mango', 7.18, 659);
insert into products (name, price, stock) values ('Beer - Labatt Blue', 14.11, 568);
insert into products (name, price, stock) values ('Chocolate - Milk Coating', 12.36, 819);
insert into products (name, price, stock) values ('Truffle Cups - Red', 6.21, 979);
insert into products (name, price, stock) values ('Cheese - Oka', 2.8, 693);
insert into products (name, price, stock) values ('Pastry - Choclate Baked', 1.44, 904);
insert into products (name, price, stock) values ('Salt - Sea', 9.29, 536);
insert into products (name, price, stock) values ('Appetizer - Smoked Salmon / Dill', 7.62, 843);
insert into products (name, price, stock) values ('Wine - Cabernet Sauvignon', 17.33, 854);
insert into products (name, price, stock) values ('Oil - Shortening,liqud, Fry', 9.1, 674);
insert into products (name, price, stock) values ('Wiberg Cure', 3.53, 837);
insert into products (name, price, stock) values ('Bagelers - Cinn / Brown', 14.13, 976);
insert into products (name, price, stock) values ('Momiji Oroshi Chili Sauce', 5.63, 977);
insert into products (name, price, stock) values ('Cheese - Cheddarsliced', 17.21, 698);
insert into products (name, price, stock) values ('Oregano - Dry, Rubbed', 17.56, 623);
insert into products (name, price, stock) values ('Veal - Striploin', 13.32, 650);
insert into products (name, price, stock) values ('Nantucket Pine Orangebanana', 11.55, 722);
insert into products (name, price, stock) values ('Cookies Almond Hazelnut', 15.05, 678);
insert into products (name, price, stock) values ('Tuna - Fresh', 2.6, 539);
insert into products (name, price, stock) values ('Pastry - Chocolate Chip Muffin', 3.12, 781);
insert into products (name, price, stock) values ('Rice - 7 Grain Blend', 4.85, 944);
insert into products (name, price, stock) values ('Orange - Canned, Mandarin', 10.55, 695);
insert into products (name, price, stock) values ('Pasta - Fusili, Dry', 11.83, 755);
insert into products (name, price, stock) values ('Cheese - Feta', 6.52, 636);
insert into products (name, price, stock) values ('Couscous', 14.84, 664);
insert into products (name, price, stock) values ('Sponge Cake Mix - Vanilla', 14.4, 686);
insert into products (name, price, stock) values ('Squid - U - 10 Thailand', 15.19, 694);
insert into products (name, price, stock) values ('Gin - Gilbeys London, Dry', 1.05, 977);
insert into products (name, price, stock) values ('Plate Pie Foil', 10.06, 944);
insert into products (name, price, stock) values ('Beef - Cooked, Corned', 4.33, 765);
insert into products (name, price, stock) values ('Bread - Roll, Calabrese', 17.57, 842);
insert into products (name, price, stock) values ('Silicone Parch. 16.3x24.3', 19.55, 579);
insert into products (name, price, stock) values ('Fennel', 2.67, 708);
insert into products (name, price, stock) values ('Lamb Shoulder Boneless Nz', 12.97, 643);
insert into products (name, price, stock) values ('Lettuce - Arugula', 14.73, 913);
insert into products (name, price, stock) values ('Cake - Night And Day Choclate', 17.7, 611);
insert into products (name, price, stock) values ('Jello - Assorted', 1.32, 760);
insert into products (name, price, stock) values ('Wine - Guy Sage Touraine', 16.65, 901);
insert into products (name, price, stock) values ('Mudslide', 8.58, 818);
insert into products (name, price, stock) values ('Syrup - Monin, Swiss Choclate', 10.99, 818);
insert into products (name, price, stock) values ('Pork - European Side Bacon', 2.84, 771);
insert into products (name, price, stock) values ('Longos - Grilled Veg Sandwiches', 17.71, 960);
insert into products (name, price, stock) values ('Soup - Campbells, Minestrone', 1.26, 824);
insert into products (name, price, stock) values ('Lemon Balm - Fresh', 10.39, 982);
insert into products (name, price, stock) values ('Sugar - Fine', 13.58, 868);
insert into products (name, price, stock) values ('Garlic - Elephant', 1.86, 824);
insert into products (name, price, stock) values ('Foil - 4oz Custard Cup', 14.52, 574);
insert into products (name, price, stock) values ('Energy Drink - Franks Pineapple', 4.44, 576);
insert into products (name, price, stock) values ('Bread - Roll, Canadian Dinner', 9.0, 872);
insert into products (name, price, stock) values ('Jam - Apricot', 6.95, 767);
insert into products (name, price, stock) values ('Artichoke - Hearts, Canned', 8.61, 500);
insert into products (name, price, stock) values ('Foam Dinner Plate', 2.97, 518);
insert into products (name, price, stock) values ('Ecolab - Orange Frc, Cleaner', 19.41, 976);
insert into products (name, price, stock) values ('Chicken - Leg / Back Attach', 6.73, 544);
insert into products (name, price, stock) values ('Longos - Cheese Tortellini', 12.44, 668);
insert into products (name, price, stock) values ('Cheese - Parmesan Grated', 10.62, 504);
insert into products (name, price, stock) values ('Beans - Wax', 1.75, 578);
insert into products (name, price, stock) values ('Leeks - Baby, White', 10.22, 682);
insert into products (name, price, stock) values ('Chicken Thigh - Bone Out', 5.28, 658);
insert into products (name, price, stock) values ('Lobster - Tail 6 Oz', 18.92, 659);
insert into products (name, price, stock) values ('Olives - Black, Pitted', 19.26, 991);
insert into products (name, price, stock) values ('Poppy Seed', 14.25, 616);
insert into products (name, price, stock) values ('Sesame Seed', 4.14, 549);
insert into products (name, price, stock) values ('Papayas', 8.61, 886);
insert into products (name, price, stock) values ('Muffin - Bran Ind Wrpd', 4.03, 506);
insert into products (name, price, stock) values ('Artichoke - Fresh', 15.15, 658);
insert into products (name, price, stock) values ('Monkfish Fresh - Skin Off', 16.89, 949);
insert into products (name, price, stock) values ('Olive - Spread Tapenade', 12.38, 737);
insert into products (name, price, stock) values ('Tart Shells - Sweet, 3', 19.03, 830);
insert into products (name, price, stock) values ('Pepper - Paprika, Spanish', 9.57, 666);
insert into products (name, price, stock) values ('Chicken - Whole Fryers', 15.16, 760);
insert into products (name, price, stock) values ('Cheese - Shred Cheddar / Mozza', 7.72, 948);
insert into products (name, price, stock) values ('Pails With Lids', 11.3, 720);
insert into products (name, price, stock) values ('Longos - Chicken Cordon Bleu', 3.55, 734);
insert into products (name, price, stock) values ('Rice - Aborio', 4.06, 660);
insert into products (name, price, stock) values ('Steamers White', 13.47, 719);
insert into products (name, price, stock) values ('Salt - Kosher', 15.55, 994);
insert into products (name, price, stock) values ('Stock - Beef, White', 7.41, 780);
insert into products (name, price, stock) values ('Syrup - Monin, Swiss Choclate', 8.66, 808);
insert into products (name, price, stock) values ('Tomato Paste', 13.77, 764);
insert into products (name, price, stock) values ('Bread - Italian Corn Meal Poly', 17.72, 550);
insert into products (name, price, stock) values ('Wine - Maipo Valle Cabernet', 10.64, 650);
insert into products (name, price, stock) values ('Rosemary - Fresh', 15.58, 867);
insert into products (name, price, stock) values ('Sugar - Fine', 12.62, 518);
insert into products (name, price, stock) values ('Apple - Macintosh', 4.11, 871);
insert into products (name, price, stock) values ('Vinegar - Rice', 15.42, 644);
insert into products (name, price, stock) values ('Beans - Long, Chinese', 16.15, 892);
insert into products (name, price, stock) values ('Sugar - White Packet', 19.37, 698);
insert into products (name, price, stock) values ('Heavy Duty Dust Pan', 2.07, 951);
insert into products (name, price, stock) values ('Wine - Cave Springs Dry Riesling', 15.95, 684);
insert into products (name, price, stock) values ('Octopus - Baby, Cleaned', 19.02, 901);
insert into products (name, price, stock) values ('Tray - 16in Rnd Blk', 4.63, 752);
insert into products (name, price, stock) values ('Pasta - Fettuccine, Dry', 5.96, 513);
insert into products (name, price, stock) values ('Pear - Halves', 5.42, 982);
insert into products (name, price, stock) values ('Gelatine Leaves - Bulk', 3.38, 524);
insert into products (name, price, stock) values ('Muffins - Assorted', 19.15, 603);
insert into products (name, price, stock) values ('Bagel - Ched Chs Presliced', 3.84, 812);
insert into products (name, price, stock) values ('Beans - Black Bean, Preserved', 18.66, 551);
insert into products (name, price, stock) values ('Juice - Apple Cider', 12.14, 875);
insert into products (name, price, stock) values ('Nut - Cashews, Whole, Raw', 14.58, 649);
insert into products (name, price, stock) values ('Mushroom - Chanterelle Frozen', 10.95, 972);
insert into products (name, price, stock) values ('Chips Potato Swt Chilli Sour', 16.77, 788);
insert into products (name, price, stock) values ('Shrimp - Prawn', 13.45, 791);
insert into products (name, price, stock) values ('Amarula Cream', 16.43, 517);
insert into products (name, price, stock) values ('Wine - Mas Chicet Rose, Vintage', 5.71, 783);
insert into products (name, price, stock) values ('Oil - Truffle, Black', 18.2, 912);
insert into products (name, price, stock) values ('Cookies - Englishbay Oatmeal', 19.1, 689);
insert into products (name, price, stock) values ('Vinegar - Sherry', 17.94, 885);
insert into products (name, price, stock) values ('Split Peas - Green, Dry', 18.69, 619);
insert into products (name, price, stock) values ('Soup - Campbells Beef Noodle', 18.67, 501);
insert into products (name, price, stock) values ('Jam - Strawberry, 20 Ml Jar', 17.32, 955);
insert into products (name, price, stock) values ('Lettuce - Arugula', 10.3, 616);
insert into products (name, price, stock) values ('Soup - Cream Of Broccoli', 6.76, 857);
insert into products (name, price, stock) values ('Crab - Imitation Flakes', 13.38, 639);
insert into products (name, price, stock) values ('Pail For Lid 1537', 19.6, 929);
insert into products (name, price, stock) values ('Carbonated Water - Orange', 2.57, 787);
insert into products (name, price, stock) values ('Oranges - Navel, 72', 16.46, 833);
insert into products (name, price, stock) values ('Coconut Milk - Unsweetened', 15.08, 906);
insert into products (name, price, stock) values ('Chef Hat 25cm', 14.15, 999);
insert into products (name, price, stock) values ('Grapes - Red', 2.62, 918);
insert into products (name, price, stock) values ('Lychee - Canned', 17.11, 655);
insert into products (name, price, stock) values ('Cake - Bande Of Fruit', 6.14, 798);
insert into products (name, price, stock) values ('Wine - Bouchard La Vignee Pinot', 1.92, 677);
insert into products (name, price, stock) values ('Nut - Chestnuts, Whole', 7.39, 662);
insert into products (name, price, stock) values ('Puree - Blackcurrant', 4.41, 896);
insert into products (name, price, stock) values ('Trueblue - Blueberry 12x473ml', 9.08, 509);
insert into products (name, price, stock) values ('Veal - Insides, Grains', 3.31, 574);
insert into products (name, price, stock) values ('Cookies - Amaretto', 17.34, 966);
insert into products (name, price, stock) values ('Meldea Green Tea Liquor', 5.59, 968);
insert into products (name, price, stock) values ('Grenadine', 4.58, 962);
insert into products (name, price, stock) values ('Table Cloth - 53x69 Colour', 15.76, 840);
insert into products (name, price, stock) values ('Ice Cream - Vanilla', 1.88, 700);
insert into products (name, price, stock) values ('Chicken Breast Halal', 14.14, 534);
insert into products (name, price, stock) values ('Crab - Meat Combo', 1.17, 586);
insert into products (name, price, stock) values ('Pizza Pizza Dough', 10.5, 988);
insert into products (name, price, stock) values ('Pepper - Pablano', 10.26, 634);
insert into products (name, price, stock) values ('Ham - Virginia', 8.94, 581);
insert into products (name, price, stock) values ('Clam Nectar', 1.83, 557);
insert into products (name, price, stock) values ('Wine - Vouvray Cuvee Domaine', 1.28, 777);
insert into products (name, price, stock) values ('Rice - Sushi', 11.05, 596);
insert into products (name, price, stock) values ('Carroway Seed', 4.3, 962);
insert into products (name, price, stock) values ('Asparagus - White, Fresh', 7.45, 517);
insert into products (name, price, stock) values ('Pizza Pizza Dough', 7.66, 846);
insert into products (name, price, stock) values ('Allspice - Jamaican', 5.88, 500);
insert into products (name, price, stock) values ('Mikes Hard Lemonade', 9.35, 714);
insert into products (name, price, stock) values ('Oysters - Smoked', 13.05, 671);
insert into products (name, price, stock) values ('Oysters - Smoked', 15.86, 980);
insert into products (name, price, stock) values ('Carbonated Water - Orange', 19.58, 987);
insert into products (name, price, stock) values ('Eel Fresh', 2.62, 829);
insert into products (name, price, stock) values ('Bread - Onion Focaccia', 17.14, 565);
insert into products (name, price, stock) values ('Easy Off Oven Cleaner', 19.61, 587);
insert into products (name, price, stock) values ('Bread - Petit Baguette', 15.11, 591);
insert into products (name, price, stock) values ('Foam Espresso Cup Plain White', 12.14, 978);
insert into products (name, price, stock) values ('Wine - Valpolicella Masi', 18.19, 920);
insert into products (name, price, stock) values ('Pickles - Gherkins', 5.09, 787);
insert into products (name, price, stock) values ('Cookies - Englishbay Chochip', 7.89, 712);
insert into products (name, price, stock) values ('Soup - Campbells Beef Stew', 18.72, 726);
insert into products (name, price, stock) values ('Pepsi, 355 Ml', 15.58, 959);
insert into products (name, price, stock) values ('Jagermeister', 17.52, 616);
insert into products (name, price, stock) values ('Wine - Zonnebloem Pinotage', 8.71, 672);
insert into products (name, price, stock) values ('Orange Roughy 6/8 Oz', 14.13, 686);
insert into products (name, price, stock) values ('Water Chestnut - Canned', 2.66, 601);
insert into products (name, price, stock) values ('Pesto - Primerba, Paste', 9.58, 995);
insert into products (name, price, stock) values ('Beef - Bresaola', 18.56, 617);
insert into products (name, price, stock) values ('Chips - Assorted', 9.59, 919);
insert into products (name, price, stock) values ('Lighter - Bbq', 8.4, 709);
insert into products (name, price, stock) values ('Bread Cranberry Foccacia', 19.04, 661);
insert into products (name, price, stock) values ('Garbage Bags - Black', 2.34, 702);
insert into products (name, price, stock) values ('Pear - Prickly', 6.95, 719);
insert into products (name, price, stock) values ('Tea Leaves - Oolong', 11.61, 761);
insert into products (name, price, stock) values ('Potatoes - Peeled', 7.8, 973);
insert into products (name, price, stock) values ('Cream Of Tartar', 10.55, 655);
insert into products (name, price, stock) values ('Sauce - Vodka Blush', 7.41, 633);
insert into products (name, price, stock) values ('Salt - Rock, Course', 14.25, 640);
insert into products (name, price, stock) values ('Beer - Mill St Organic', 15.08, 792);
insert into products (name, price, stock) values ('Chocolate - Unsweetened', 16.42, 801);
insert into products (name, price, stock) values ('Arrowroot', 2.91, 861);
insert into products (name, price, stock) values ('Plastic Arrow Stir Stick', 7.37, 820);
insert into products (name, price, stock) values ('Gin - Gilbeys London, Dry', 13.71, 753);
insert into products (name, price, stock) values ('Ice Cream - Vanilla', 9.67, 817);
insert into products (name, price, stock) values ('Dr. Pepper - 355ml', 7.47, 805);
insert into products (name, price, stock) values ('Sprouts - Onion', 10.56, 897);
insert into products (name, price, stock) values ('Quail - Whole, Boneless', 11.72, 753);
insert into products (name, price, stock) values ('Garlic Powder', 18.03, 918);
insert into products (name, price, stock) values ('Mushroom - Trumpet, Dry', 18.56, 558);
insert into products (name, price, stock) values ('Cake - Lemon Chiffon', 14.17, 863);
insert into products (name, price, stock) values ('Mackerel Whole Fresh', 18.33, 710);
insert into products (name, price, stock) values ('Corn Meal', 18.43, 707);
insert into products (name, price, stock) values ('Pur Source', 14.96, 752);
insert into products (name, price, stock) values ('Canada Dry', 12.21, 860);
insert into products (name, price, stock) values ('Wine - Red, Concha Y Toro', 15.64, 663);
insert into products (name, price, stock) values ('Lettuce - Lolla Rosa', 2.81, 739);
insert into products (name, price, stock) values ('Apple - Macintosh', 19.28, 681);
insert into products (name, price, stock) values ('Port - 74 Brights', 15.85, 758);
insert into products (name, price, stock) values ('Cheese - Pont Couvert', 14.4, 669);
insert into products (name, price, stock) values ('Bandage - Flexible Neon', 2.33, 559);
insert into products (name, price, stock) values ('Nantucket Orange Juice', 14.7, 731);
insert into products (name, price, stock) values ('Marsala - Sperone, Fine, D.o.c.', 2.69, 610);
insert into products (name, price, stock) values ('Island Oasis - Pina Colada', 10.2, 974);
insert into products (name, price, stock) values ('Water - Green Tea Refresher', 7.43, 738);
insert into products (name, price, stock) values ('Eggplant Oriental', 9.77, 558);
insert into products (name, price, stock) values ('Lambcasing', 12.81, 592);
insert into products (name, price, stock) values ('Toothpick Frilled', 6.67, 528);
insert into products (name, price, stock) values ('Juice - Apple Cider', 8.99, 581);
insert into products (name, price, stock) values ('Salmon - Fillets', 11.36, 955);
insert into products (name, price, stock) values ('Artichoke - Fresh', 7.63, 874);
insert into products (name, price, stock) values ('Longos - Burritos', 14.76, 733);
insert into products (name, price, stock) values ('Cloves - Ground', 9.37, 983);
insert into products (name, price, stock) values ('Soup - Campbells, Minestrone', 1.45, 993);
insert into products (name, price, stock) values ('Beer - Original Organic Lager', 15.38, 843);
insert into products (name, price, stock) values ('Juice - Ocean Spray Cranberry', 12.66, 564);
insert into products (name, price, stock) values ('Pea - Snow', 8.36, 679);
insert into products (name, price, stock) values ('Marsala - Sperone, Fine, D.o.c.', 9.31, 651);
insert into products (name, price, stock) values ('Ecolab Digiclean Mild Fm', 14.78, 608);
insert into products (name, price, stock) values ('Bread - Wheat Baguette', 9.47, 779);
insert into products (name, price, stock) values ('Beef - Rib Eye Aaa', 19.48, 780);
insert into products (name, price, stock) values ('Barramundi', 17.29, 652);
insert into products (name, price, stock) values ('Veal - Striploin', 16.99, 868);
insert into products (name, price, stock) values ('Cocoa Powder - Natural', 16.95, 630);
insert into products (name, price, stock) values ('Wonton Wrappers', 9.57, 920);
insert into products (name, price, stock) values ('Milk 2% 500 Ml', 10.62, 688);
insert into products (name, price, stock) values ('Chips - Assorted', 1.69, 665);
insert into products (name, price, stock) values ('Veal - Leg, Provimi - 50 Lb Max', 9.44, 807);
insert into products (name, price, stock) values ('Bagel - Everything', 18.29, 744);
insert into products (name, price, stock) values ('Pork - Back Ribs', 11.76, 657);
insert into products (name, price, stock) values ('Asparagus - White, Fresh', 14.05, 523);
insert into products (name, price, stock) values ('Wine - Sicilia Igt Nero Avola', 6.32, 808);
insert into products (name, price, stock) values ('Pork - Ham Hocks - Smoked', 11.14, 727);
insert into products (name, price, stock) values ('Wine - Shiraz South Eastern', 11.61, 627);
insert into products (name, price, stock) values ('Tomato - Tricolor Cherry', 5.7, 636);
insert into products (name, price, stock) values ('Pomegranates', 9.34, 809);
insert into products (name, price, stock) values ('Wine - Harrow Estates, Vidal', 16.76, 647);
insert into products (name, price, stock) values ('Steampan - Foil', 15.92, 861);
insert into products (name, price, stock) values ('Soup - Campbells Beef Noodle', 6.31, 703);
insert into products (name, price, stock) values ('Chip - Potato Dill Pickle', 1.6, 648);
insert into products (name, price, stock) values ('Cup - 3.5oz, Foam', 12.45, 660);
insert into products (name, price, stock) values ('Butter Ripple - Phillips', 15.88, 740);
insert into products (name, price, stock) values ('Alize Red Passion', 18.18, 501);
insert into products (name, price, stock) values ('Chicken - Livers', 14.06, 799);
insert into products (name, price, stock) values ('Crab - Dungeness, Whole', 9.66, 646);
insert into products (name, price, stock) values ('Rum - Light, Captain Morgan', 19.66, 825);
insert into products (name, price, stock) values ('Glaze - Clear', 8.43, 940);
insert into products (name, price, stock) values ('Beef Flat Iron Steak', 6.58, 580);
insert into products (name, price, stock) values ('Cup - 3.5oz, Foam', 14.7, 542);
insert into products (name, price, stock) values ('Pasta - Orecchiette', 7.56, 533);
insert into products (name, price, stock) values ('Cloves - Whole', 13.93, 656);
insert into products (name, price, stock) values ('Irish Cream - Baileys', 10.2, 893);
insert into products (name, price, stock) values ('Fondant - Icing', 17.36, 570);
insert into products (name, price, stock) values ('Basil - Primerba, Paste', 13.65, 594);
insert into products (name, price, stock) values ('Wine - White, Pinot Grigio', 10.27, 729);
insert into products (name, price, stock) values ('Wine - Red, Mosaic Zweigelt', 14.5, 709);
insert into products (name, price, stock) values ('Sauce - Soya, Dark', 2.82, 806);
insert into products (name, price, stock) values ('Sprouts - Brussel', 12.14, 860);
insert into products (name, price, stock) values ('Longos - Penne With Pesto', 15.34, 740);
insert into products (name, price, stock) values ('Chervil - Fresh', 6.7, 803);
insert into products (name, price, stock) values ('Bagel - Plain', 14.25, 933);
insert into products (name, price, stock) values ('Veal - Brisket, Provimi, Bone - In', 11.83, 610);
insert into products (name, price, stock) values ('Soup - Campbells, Creamy', 16.39, 541);
insert into products (name, price, stock) values ('Coffee - Beans, Whole', 1.72, 995);
insert into products (name, price, stock) values ('Wine - Chablis 2003 Champs', 15.56, 577);
insert into products (name, price, stock) values ('Table Cloth 120 Round White', 14.05, 980);
insert into products (name, price, stock) values ('Juice - Mango', 8.9, 724);
insert into products (name, price, stock) values ('7up Diet, 355 Ml', 10.12, 563);
insert into products (name, price, stock) values ('Gatorade - Fruit Punch', 11.43, 750);
insert into products (name, price, stock) values ('Milk 2% 500 Ml', 8.79, 816);
insert into products (name, price, stock) values ('Soup - Cream Of Potato / Leek', 9.7, 875);
insert into products (name, price, stock) values ('Wine - White, Ej', 14.5, 557);
insert into products (name, price, stock) values ('Butter - Pod', 5.06, 817);
insert into products (name, price, stock) values ('Sage - Fresh', 19.39, 556);
insert into products (name, price, stock) values ('Wine - White, Schroder And Schyl', 13.51, 798);
insert into products (name, price, stock) values ('Chocolate Bar - Smarties', 4.26, 685);
insert into products (name, price, stock) values ('Orange - Blood', 14.61, 824);
insert into products (name, price, stock) values ('Capers - Pickled', 8.3, 911);
insert into products (name, price, stock) values ('Glucose', 6.93, 573);
insert into products (name, price, stock) values ('Sugar - Sweet N Low, Individual', 13.51, 616);
insert into products (name, price, stock) values ('Tuna - Yellowfin', 3.85, 681);
insert into products (name, price, stock) values ('Brownies - Two Bite, Chocolate', 3.49, 662);
insert into products (name, price, stock) values ('Sugar - Invert', 19.93, 714);
insert into products (name, price, stock) values ('Pasta - Lasagna Noodle, Frozen', 4.1, 562);
insert into products (name, price, stock) values ('Lemonade - Natural, 591 Ml', 6.46, 884);
insert into products (name, price, stock) values ('Bread - Pumpernickle, Rounds', 4.3, 804);
insert into products (name, price, stock) values ('Lamb - Sausage Casings', 1.23, 618);
insert into products (name, price, stock) values ('Pasta - Penne, Rigate, Dry', 14.52, 526);
insert into products (name, price, stock) values ('Chocolate - Mi - Amere Semi', 18.02, 824);
insert into products (name, price, stock) values ('Pepper - White, Whole', 1.21, 962);
insert into products (name, price, stock) values ('Cup - 6oz, Foam', 6.45, 806);
insert into products (name, price, stock) values ('Pastry - Plain Baked Croissant', 12.86, 919);
insert into products (name, price, stock) values ('Beef - Short Ribs', 7.49, 922);
insert into products (name, price, stock) values ('Pepper - Scotch Bonnet', 15.25, 616);
insert into products (name, price, stock) values ('Sprouts - Pea', 11.35, 587);
insert into products (name, price, stock) values ('Calypso - Lemonade', 17.14, 874);
insert into products (name, price, stock) values ('Seedlings - Mix, Organic', 9.14, 693);
insert into products (name, price, stock) values ('Apricots Fresh', 8.48, 709);
insert into products (name, price, stock) values ('Cookies - Englishbay Chochip', 15.48, 827);
insert into products (name, price, stock) values ('Sloe Gin - Mcguinness', 5.4, 604);
insert into products (name, price, stock) values ('Yucca', 7.88, 526);
insert into products (name, price, stock) values ('Napkin White', 18.76, 900);
insert into products (name, price, stock) values ('Sage Ground Wiberg', 17.5, 725);
insert into products (name, price, stock) values ('Mousse - Passion Fruit', 5.14, 818);
insert into products (name, price, stock) values ('Bread - Dark Rye', 19.77, 964);
insert into products (name, price, stock) values ('Foam Dinner Plate', 1.8, 928);
insert into products (name, price, stock) values ('Watercress', 1.62, 550);
insert into products (name, price, stock) values ('Beef - Rib Roast, Capless', 17.44, 925);
insert into products (name, price, stock) values ('Dates', 19.51, 994);
insert into products (name, price, stock) values ('Soup - Campbells Beef Stew', 14.84, 654);
insert into products (name, price, stock) values ('Chinese Lemon Pork', 8.39, 969);
insert into products (name, price, stock) values ('Wine - Masi Valpolocell', 13.04, 545);
insert into products (name, price, stock) values ('Sage - Rubbed', 4.21, 532);
insert into products (name, price, stock) values ('Pepper Squash', 3.11, 635);
insert into products (name, price, stock) values ('Salt - Celery', 16.99, 849);
insert into products (name, price, stock) values ('Pie Shells 10', 9.91, 525);
insert into products (name, price, stock) values ('Tortillas - Flour, 8', 14.11, 567);
insert into products (name, price, stock) values ('Bread - Triangle White', 11.26, 970);
insert into products (name, price, stock) values ('Sugar - Fine', 7.11, 790);
insert into products (name, price, stock) values ('Soup Campbells - Tomato Bisque', 6.77, 767);
insert into products (name, price, stock) values ('Energy Drink - Franks Pineapple', 12.55, 528);
insert into products (name, price, stock) values ('Tomatoes - Orange', 6.6, 976);
insert into products (name, price, stock) values ('Bread - White, Sliced', 5.56, 657);
insert into products (name, price, stock) values ('Pork - Sausage Casing', 6.14, 808);
insert into products (name, price, stock) values ('Bar Mix - Pina Colada, 355 Ml', 10.77, 534);
insert into products (name, price, stock) values ('Muffin Hinge Container 6', 8.8, 573);
insert into products (name, price, stock) values ('Beef - Top Butt', 7.71, 793);
insert into products (name, price, stock) values ('Pie Shells 10', 18.08, 555);
insert into products (name, price, stock) values ('Snails - Large Canned', 16.0, 570);
insert into products (name, price, stock) values ('Beans - Long, Chinese', 12.84, 582);
insert into products (name, price, stock) values ('Beef - Top Sirloin - Aaa', 1.54, 821);
insert into products (name, price, stock) values ('Veal - Heart', 13.79, 888);
insert into products (name, price, stock) values ('Beef - Tongue, Cooked', 17.85, 880);
insert into products (name, price, stock) values ('Wine - Chenin Blanc K.w.v.', 2.28, 512);
insert into products (name, price, stock) values ('Bread - Flat Bread', 10.09, 545);
insert into products (name, price, stock) values ('Plaintain', 14.18, 558);
insert into products (name, price, stock) values ('Duck - Breast', 5.29, 502);
insert into products (name, price, stock) values ('Turkey - Breast, Smoked', 11.2, 574);
insert into products (name, price, stock) values ('Catfish - Fillets', 7.75, 665);
insert into products (name, price, stock) values ('Chef Hat 25cm', 19.96, 847);
insert into products (name, price, stock) values ('Onions - Cooking', 8.74, 877);
insert into products (name, price, stock) values ('Nut - Hazelnut, Ground, Natural', 17.99, 805);
insert into products (name, price, stock) values ('Ecolab - Hobart Washarm End Cap', 8.3, 959);
insert into products (name, price, stock) values ('Cassis', 3.26, 866);
insert into products (name, price, stock) values ('Wine - White, Gewurtzraminer', 17.93, 842);
insert into products (name, price, stock) values ('Pasta - Fett Alfredo, Single Serve', 9.97, 647);
insert into products (name, price, stock) values ('Instant Coffee', 2.48, 515);
insert into products (name, price, stock) values ('Cocoa Powder - Dutched', 12.25, 815);
insert into products (name, price, stock) values ('Monkfish - Fresh', 18.12, 692);
insert into products (name, price, stock) values ('Pie Filling - Cherry', 18.07, 810);
insert into products (name, price, stock) values ('Rice - Wild', 16.46, 722);
insert into products (name, price, stock) values ('Water, Tap', 19.31, 983);
insert into products (name, price, stock) values ('Chinese Lemon Pork', 15.89, 829);
insert into products (name, price, stock) values ('Apple - Macintosh', 14.33, 979);
insert into products (name, price, stock) values ('Seabream Whole Farmed', 4.44, 624);
insert into products (name, price, stock) values ('Flour - Masa De Harina Mexican', 13.03, 654);
insert into products (name, price, stock) values ('Lettuce - California Mix', 15.68, 838);
insert into products (name, price, stock) values ('Shrimp - Black Tiger 26/30', 17.71, 755);
insert into products (name, price, stock) values ('Cod - Salted, Boneless', 14.66, 736);
insert into products (name, price, stock) values ('French Kiss Vanilla', 1.91, 985);
insert into products (name, price, stock) values ('Carrots - Mini, Stem On', 2.14, 733);
insert into products (name, price, stock) values ('Veal Inside - Provimi', 4.87, 954);
insert into products (name, price, stock) values ('Soup - Knorr, Ministrone', 10.54, 710);
insert into products (name, price, stock) values ('Beer - Guiness', 11.01, 943);
insert into products (name, price, stock) values ('Towel Dispenser', 11.79, 811);
insert into products (name, price, stock) values ('Puree - Guava', 10.61, 900);
insert into products (name, price, stock) values ('Cheese Cloth No 60', 11.29, 962);
insert into products (name, price, stock) values ('Wine - Zonnebloem Pinotage', 11.82, 579);
insert into products (name, price, stock) values ('Sole - Iqf', 15.08, 702);
insert into products (name, price, stock) values ('Soho Lychee Liqueur', 9.42, 878);
insert into products (name, price, stock) values ('Beef - Ground Lean Fresh', 1.66, 580);
insert into products (name, price, stock) values ('Muffin Mix - Oatmeal', 7.98, 802);
insert into products (name, price, stock) values ('Spice - Pepper Portions', 18.18, 863);
insert into products (name, price, stock) values ('Sauce - Marinara', 12.11, 651);
insert into products (name, price, stock) values ('Spring Roll Veg Mini', 16.75, 858);
insert into products (name, price, stock) values ('Beer - Creemore', 16.31, 506);
insert into products (name, price, stock) values ('Apples - Sliced / Wedge', 15.29, 602);
insert into products (name, price, stock) values ('Bread - Pita, Mini', 16.47, 807);
insert into products (name, price, stock) values ('Pork - Back, Short Cut, Boneless', 1.16, 680);
insert into products (name, price, stock) values ('Plate - Foam, Bread And Butter', 6.47, 760);
insert into products (name, price, stock) values ('Squid - Tubes / Tenticles 10/20', 4.42, 753);
insert into products (name, price, stock) values ('Fond - Chocolate', 15.18, 733);
insert into products (name, price, stock) values ('Lamb - Shoulder', 2.46, 803);
insert into products (name, price, stock) values ('Truffle Cups - Brown', 7.58, 737);
insert into products (name, price, stock) values ('Yogurt - Plain', 1.87, 514);
insert into products (name, price, stock) values ('Wine - Gewurztraminer Pierre', 3.27, 757);
insert into products (name, price, stock) values ('Pepper - Black, Whole', 16.63, 808);
insert into products (name, price, stock) values ('Muffin Chocolate Individual Wrap', 14.49, 588);
insert into products (name, price, stock) values ('Yoghurt Tubes', 19.14, 605);
insert into products (name, price, stock) values ('Pastry - Banana Muffin - Mini', 16.28, 925);
insert into products (name, price, stock) values ('Turkey - Breast, Bone - In', 9.05, 973);
insert into products (name, price, stock) values ('Coffee Swiss Choc Almond', 17.7, 821);
insert into products (name, price, stock) values ('Towel - Roll White', 17.35, 541);
insert into products (name, price, stock) values ('Chicken - Bones', 18.01, 885);
insert into products (name, price, stock) values ('Beer - Fruli', 6.69, 894);
insert into products (name, price, stock) values ('Cheese - Brie,danish', 14.57, 871);
insert into products (name, price, stock) values ('Shrimp - Baby, Warm Water', 1.2, 558);
insert into products (name, price, stock) values ('Garam Masala Powder', 14.16, 574);
insert into products (name, price, stock) values ('Wine - Fume Blanc Fetzer', 19.6, 569);
insert into products (name, price, stock) values ('Beets - Candy Cane, Organic', 6.43, 512);
insert into products (name, price, stock) values ('Napkin Colour', 18.55, 591);
insert into products (name, price, stock) values ('Rice Wine - Aji Mirin', 3.93, 597);
insert into products (name, price, stock) values ('Squash - Butternut', 9.19, 891);
insert into products (name, price, stock) values ('Coffee - Colombian, Portioned', 4.6, 955);
insert into products (name, price, stock) values ('Steam Pan Full Lid', 6.89, 969);
insert into products (name, price, stock) values ('Ranchero - Primerba, Paste', 19.13, 814);
insert into products (name, price, stock) values ('Bread - Focaccia Quarter', 14.56, 544);
insert into products (name, price, stock) values ('Crackers - Trio', 14.51, 612);
insert into products (name, price, stock) values ('Sugar - Crumb', 4.51, 997);
insert into products (name, price, stock) values ('Chocolate - Chips Compound', 14.05, 776);
insert into products (name, price, stock) values ('Bread - White Mini Epi', 8.57, 635);
insert into products (name, price, stock) values ('Muffin - Zero Transfat', 3.21, 692);
insert into products (name, price, stock) values ('Wine - Rubyport', 16.44, 784);
insert into products (name, price, stock) values ('Lamb - Loin, Trimmed, Boneless', 2.97, 708);
insert into products (name, price, stock) values ('V8 - Vegetable Cocktail', 15.08, 645);
insert into products (name, price, stock) values ('Sparkling Wine - Rose, Freixenet', 15.5, 907);
insert into products (name, price, stock) values ('Wine - Pinot Grigio Collavini', 14.14, 654);
insert into products (name, price, stock) values ('Beer - Original Organic Lager', 7.94, 903);
insert into products (name, price, stock) values ('Wine - Chateau Aqueria Tavel', 12.31, 677);
insert into products (name, price, stock) values ('Extract Vanilla Pure', 18.64, 651);
insert into products (name, price, stock) values ('Sauce - Salsa', 17.11, 718);
insert into products (name, price, stock) values ('Gatorade - Xfactor Berry', 12.55, 945);
insert into products (name, price, stock) values ('Basil - Fresh', 6.38, 593);
insert into products (name, price, stock) values ('Soup - Campbells, Beef Barley', 1.27, 805);
insert into products (name, price, stock) values ('Bread - Pumpernickel', 18.72, 744);
insert into products (name, price, stock) values ('Wine - Charddonnay Errazuriz', 8.95, 645);
insert into products (name, price, stock) values ('Octopus - Baby, Cleaned', 4.16, 729);
insert into products (name, price, stock) values ('Carbonated Water - Cherry', 9.66, 962);
insert into products (name, price, stock) values ('Maple Syrup', 8.35, 627);
insert into products (name, price, stock) values ('Skirt - 29 Foot', 3.72, 845);
insert into products (name, price, stock) values ('Pop Shoppe Cream Soda', 4.31, 611);
insert into products (name, price, stock) values ('Wine - Merlot Vina Carmen', 17.41, 845);
insert into products (name, price, stock) values ('Bay Leaf Fresh', 11.7, 953);
insert into products (name, price, stock) values ('Ginger - Ground', 16.65, 873);
insert into products (name, price, stock) values ('Beef Cheek Fresh', 17.67, 892);
insert into products (name, price, stock) values ('Seedlings - Buckwheat, Organic', 13.77, 522);
insert into products (name, price, stock) values ('7up Diet, 355 Ml', 6.8, 813);
insert into products (name, price, stock) values ('Pasta - Spaghetti, Dry', 19.91, 723);
insert into products (name, price, stock) values ('Sambuca - Ramazzotti', 11.97, 937);
insert into products (name, price, stock) values ('Pernod', 19.2, 519);
insert into products (name, price, stock) values ('Remy Red Berry Infusion', 17.61, 973);
insert into products (name, price, stock) values ('Bread - Raisin', 9.17, 814);
insert into products (name, price, stock) values ('Bread - Bagels, Plain', 14.54, 843);
insert into products (name, price, stock) values ('Parsley - Dried', 5.33, 812);
insert into products (name, price, stock) values ('Sugar - Fine', 7.83, 544);
insert into products (name, price, stock) values ('Beans - Fine', 15.64, 746);
insert into products (name, price, stock) values ('Beer - Alexander Kieths, Pale Ale', 1.21, 746);
insert into products (name, price, stock) values ('Sausage - Liver', 13.98, 808);
insert into products (name, price, stock) values ('Trueblue - Blueberry 12x473ml', 15.05, 905);
insert into products (name, price, stock) values ('Gelatine Leaves - Bulk', 13.95, 550);
insert into products (name, price, stock) values ('Ice Cream Bar - Oreo Cone', 14.08, 673);
insert into products (name, price, stock) values ('Pork - Loin, Boneless', 6.58, 768);
insert into products (name, price, stock) values ('Mix - Cocktail Strawberry Daiquiri', 8.83, 814);
insert into products (name, price, stock) values ('Juice - Cranberry, 341 Ml', 16.48, 568);
insert into products (name, price, stock) values ('Pate - Liver', 9.92, 782);
insert into products (name, price, stock) values ('Basil - Fresh', 17.93, 795);
insert into products (name, price, stock) values ('Bread Base - Goodhearth', 5.04, 911);
insert into products (name, price, stock) values ('Garam Masala Powder', 12.38, 773);
insert into products (name, price, stock) values ('Beer - Sleemans Honey Brown', 3.15, 644);
insert into products (name, price, stock) values ('Chicken - Breast, 5 - 7 Oz', 18.58, 558);
insert into products (name, price, stock) values ('Pate Pans Yellow', 3.52, 521);
insert into products (name, price, stock) values ('Scampi Tail', 19.79, 866);
insert into products (name, price, stock) values ('Pheasants - Whole', 10.07, 854);
insert into products (name, price, stock) values ('Pur Source', 9.26, 827);
insert into products (name, price, stock) values ('Plastic Wrap', 10.07, 766);
insert into products (name, price, stock) values ('Corn - On The Cob', 4.44, 892);
insert into products (name, price, stock) values ('Wine - Delicato Merlot', 10.55, 739);
insert into products (name, price, stock) values ('Garlic - Peeled', 7.82, 603);
insert into products (name, price, stock) values ('Soup - Campbells Mushroom', 4.15, 638);
insert into products (name, price, stock) values ('Broom And Brush Rack Black', 9.85, 559);
insert into products (name, price, stock) values ('Pepper - Green, Chili', 17.49, 556);
insert into products (name, price, stock) values ('Spoon - Soup, Plastic', 1.06, 676);
insert into products (name, price, stock) values ('Bread - Flat Bread', 2.04, 605);
insert into products (name, price, stock) values ('Grapes - Black', 18.35, 990);
insert into products (name, price, stock) values ('Bread - Roll, Canadian Dinner', 6.88, 640);
insert into products (name, price, stock) values ('Soup - French Onion, Dry', 13.51, 914);
insert into products (name, price, stock) values ('Wine - Lou Black Shiraz', 17.94, 712);
insert into products (name, price, stock) values ('Cheese - Woolwich Goat, Log', 8.38, 629);
insert into products (name, price, stock) values ('Red Currant Jelly', 1.3, 886);
insert into products (name, price, stock) values ('Sauce - Salsa', 8.07, 527);
insert into products (name, price, stock) values ('Wine - Saint Emilion Calvet', 4.4, 713);
insert into products (name, price, stock) values ('Kohlrabi', 17.84, 666);
insert into products (name, price, stock) values ('Trueblue - Blueberry', 11.77, 904);
insert into products (name, price, stock) values ('Slt - Individual Portions', 13.31, 889);
insert into products (name, price, stock) values ('Pears - Fiorelle', 18.45, 607);
insert into products (name, price, stock) values ('Foam Espresso Cup Plain White', 6.74, 699);
insert into products (name, price, stock) values ('Kaffir Lime Leaves', 4.22, 832);
insert into products (name, price, stock) values ('Tomatoes - Roma', 5.83, 900);
insert into products (name, price, stock) values ('Sauce - Vodka Blush', 16.65, 844);
insert into products (name, price, stock) values ('Veal - Liver', 2.43, 658);
insert into products (name, price, stock) values ('Sproutsmustard Cress', 15.21, 731);
insert into products (name, price, stock) values ('Hand Towel', 16.58, 612);
insert into products (name, price, stock) values ('Trout - Rainbow, Fresh', 7.74, 532);
insert into products (name, price, stock) values ('Spinach - Frozen', 4.22, 694);
insert into products (name, price, stock) values ('Cardamon Seed / Pod', 18.87, 873);
insert into products (name, price, stock) values ('Mushroom - Chantrelle, Fresh', 12.43, 659);
insert into products (name, price, stock) values ('Mushrooms - Honey', 11.84, 850);
insert into products (name, price, stock) values ('Eggroll', 6.98, 780);
insert into products (name, price, stock) values ('Muffin Mix - Raisin Bran', 2.69, 955);
insert into products (name, price, stock) values ('C - Plus, Orange', 16.35, 529);
insert into products (name, price, stock) values ('Soup - Campbells', 15.4, 713);
insert into products (name, price, stock) values ('Chinese Foods - Chicken', 18.49, 772);
insert into products (name, price, stock) values ('Fish - Halibut, Cold Smoked', 11.83, 691);
insert into products (name, price, stock) values ('Duck - Fat', 12.11, 868);
insert into products (name, price, stock) values ('Plaintain', 2.09, 855);
insert into products (name, price, stock) values ('Clams - Bay', 9.04, 930);
insert into products (name, price, stock) values ('Beef - Tongue, Cooked', 19.03, 968);
insert into products (name, price, stock) values ('Lettuce - Lolla Rosa', 9.71, 512);
insert into products (name, price, stock) values ('Pepper - Green Thai', 5.11, 907);
insert into products (name, price, stock) values ('Calypso - Lemonade', 5.18, 681);
insert into products (name, price, stock) values ('Apron', 2.02, 666);
insert into products (name, price, stock) values ('Zucchini - Mini, Green', 11.87, 948);
insert into products (name, price, stock) values ('Squash - Pepper', 16.68, 975);
insert into products (name, price, stock) values ('Snapple - Mango Maddness', 15.74, 531);
insert into products (name, price, stock) values ('Wine - Alsace Gewurztraminer', 5.48, 835);
insert into products (name, price, stock) values ('Water - Spring 1.5lit', 8.28, 643);
insert into products (name, price, stock) values ('Lid - 16 Oz And 32 Oz', 10.65, 625);
insert into products (name, price, stock) values ('Fondant - Icing', 3.15, 886);
insert into products (name, price, stock) values ('Carbonated Water - Strawberry', 4.47, 546);
insert into products (name, price, stock) values ('Sausage - Chorizo', 16.83, 788);
insert into products (name, price, stock) values ('Shrimp - 31/40', 8.42, 579);
insert into products (name, price, stock) values ('Wine - White, Colubia Cresh', 2.12, 681);
insert into products (name, price, stock) values ('Squash - Acorn', 1.12, 935);
insert into products (name, price, stock) values ('Juice - V8 Splash', 14.09, 954);
insert into products (name, price, stock) values ('Coffee - Hazelnut Cream', 12.86, 721);
insert into products (name, price, stock) values ('Wine - Segura Viudas Aria Brut', 17.29, 754);
insert into products (name, price, stock) values ('Sprouts - Peppercress', 10.85, 713);
insert into products (name, price, stock) values ('Apricots - Halves', 3.26, 778);
insert into products (name, price, stock) values ('Pork Salted Bellies', 18.59, 755);
insert into products (name, price, stock) values ('Cake - French Pear Tart', 2.13, 595);
insert into products (name, price, stock) values ('Wine - Zinfandel California 2002', 5.67, 956);
insert into products (name, price, stock) values ('Ice Cream - Fudge Bars', 17.31, 734);
insert into products (name, price, stock) values ('Wine - Prosecco Valdobienne', 18.31, 573);
insert into products (name, price, stock) values ('Salmon - Smoked, Sliced', 7.82, 880);
insert into products (name, price, stock) values ('Vol Au Vents', 13.6, 593);
insert into products (name, price, stock) values ('Sea Bass - Whole', 6.95, 737);
insert into products (name, price, stock) values ('Chinese Foods - Pepper Beef', 8.23, 585);
insert into products (name, price, stock) values ('Clams - Canned', 6.72, 694);
insert into products (name, price, stock) values ('Ice Cream - Fudge Bars', 5.61, 814);
insert into products (name, price, stock) values ('Flower - Dish Garden', 13.91, 971);
insert into products (name, price, stock) values ('Pasta - Fusili Tri - Coloured', 19.21, 914);
insert into products (name, price, stock) values ('Sorrel - Fresh', 3.92, 609);
insert into products (name, price, stock) values ('Swiss Chard', 11.84, 755);
insert into products (name, price, stock) values ('Artichokes - Jerusalem', 5.31, 734);
insert into products (name, price, stock) values ('Bread - Rosemary Focaccia', 1.99, 541);
insert into products (name, price, stock) values ('Bread - Burger', 4.87, 999);
insert into products (name, price, stock) values ('Wine - White, Gewurtzraminer', 7.22, 548);
insert into products (name, price, stock) values ('Sauce - Mint', 16.03, 600);
insert into products (name, price, stock) values ('Coffee - Hazelnut Cream', 2.44, 522);
insert into products (name, price, stock) values ('Wine - Rhine Riesling Wolf Blass', 18.05, 546);
insert into products (name, price, stock) values ('Sage - Ground', 16.5, 937);
insert into products (name, price, stock) values ('Muffin Mix - Blueberry', 17.75, 726);
insert into products (name, price, stock) values ('Venison - Racks Frenched', 11.15, 750);
insert into products (name, price, stock) values ('Trout Rainbow Whole', 10.32, 649);
insert into products (name, price, stock) values ('Cup - 3.5oz, Foam', 19.25, 789);
insert into products (name, price, stock) values ('Beef - Prime Rib Aaa', 6.36, 974);
insert into products (name, price, stock) values ('Bread - Olive', 10.17, 774);
insert into products (name, price, stock) values ('Greens Mustard', 12.86, 912);
insert into products (name, price, stock) values ('Marjoram - Fresh', 15.79, 621);
insert into products (name, price, stock) values ('Juice - Happy Planet', 4.29, 571);
insert into products (name, price, stock) values ('Gelatine Leaves - Bulk', 1.66, 946);
insert into products (name, price, stock) values ('Oil - Hazelnut', 4.91, 747);
insert into products (name, price, stock) values ('French Pastry - Mini Chocolate', 10.93, 667);
insert into products (name, price, stock) values ('Bowl 12 Oz - Showcase 92012', 16.57, 874);
insert into products (name, price, stock) values ('Ice Cream - Life Savers', 18.67, 845);
insert into products (name, price, stock) values ('Pie Filling - Pumpkin', 11.37, 553);
insert into products (name, price, stock) values ('Shrimp - Black Tiger 6 - 8', 2.63, 937);
insert into products (name, price, stock) values ('Cheese - Asiago', 17.48, 511);
insert into products (name, price, stock) values ('Muffin - Banana Nut Individual', 6.71, 721);
insert into products (name, price, stock) values ('Mushroom - King Eryingii', 5.77, 849);
insert into products (name, price, stock) values ('Appetizer - Seafood Assortment', 1.57, 606);
insert into products (name, price, stock) values ('Beer - Blue Light', 7.37, 848);
insert into products (name, price, stock) values ('Chick Peas - Dried', 19.71, 724);
insert into products (name, price, stock) values ('Wine - Wyndham Estate Bin 777', 10.51, 773);
insert into products (name, price, stock) values ('Isomalt', 13.17, 510);
insert into products (name, price, stock) values ('Sterno - Chafing Dish Fuel', 7.79, 963);
insert into products (name, price, stock) values ('Cheese - Parmigiano Reggiano', 1.75, 767);
insert into products (name, price, stock) values ('Cocoa Feuilletine', 10.43, 923);
insert into products (name, price, stock) values ('Milk - 2%', 13.32, 812);
insert into products (name, price, stock) values ('Pastry - Banana Muffin - Mini', 15.13, 578);
insert into products (name, price, stock) values ('Pears - Bartlett', 15.53, 606);
insert into products (name, price, stock) values ('Shrimp - 100 / 200 Cold Water', 7.39, 650);
insert into products (name, price, stock) values ('Everfresh Products', 5.63, 771);
insert into products (name, price, stock) values ('Pepper - Gypsy Pepper', 9.63, 722);
insert into products (name, price, stock) values ('Table Cloth 90x90 White', 12.71, 719);
insert into products (name, price, stock) values ('Bread - Raisin', 7.08, 950);
insert into products (name, price, stock) values ('Beets - Golden', 12.66, 861);
insert into products (name, price, stock) values ('Cookie - Dough Variety', 4.56, 631);
insert into products (name, price, stock) values ('Gelatine Powder', 19.94, 634);
insert into products (name, price, stock) values ('Beef - Top Butt Aaa', 5.34, 525);
insert into products (name, price, stock) values ('Pepsi, 355 Ml', 7.53, 735);
insert into products (name, price, stock) values ('Spinach - Baby', 18.03, 642);
insert into products (name, price, stock) values ('Glaze - Apricot', 16.33, 579);
insert into products (name, price, stock) values ('Sprouts - Bean', 19.03, 525);
insert into products (name, price, stock) values ('Cake - Pancake', 13.16, 632);
insert into products (name, price, stock) values ('Beef - Tongue, Cooked', 19.22, 930);
insert into products (name, price, stock) values ('Buffalo - Tenderloin', 15.72, 605);
insert into products (name, price, stock) values ('Berry Brulee', 6.53, 730);
insert into products (name, price, stock) values ('Duck - Fat', 17.15, 993);
insert into products (name, price, stock) values ('Pepper - Black, Ground', 16.82, 978);
insert into products (name, price, stock) values ('Cardamon Ground', 5.9, 912);
insert into products (name, price, stock) values ('Cleaner - Lime Away', 14.25, 790);
insert into products (name, price, stock) values ('Mushroom - White Button', 18.7, 958);
insert into products (name, price, stock) values ('Potatoes - Mini Red', 17.39, 769);
insert into products (name, price, stock) values ('Petit Baguette', 10.5, 667);
insert into products (name, price, stock) values ('Wine - Red, Gamay Noir', 18.21, 818);
insert into products (name, price, stock) values ('Baking Powder', 12.78, 810);
insert into products (name, price, stock) values ('Soup - Cream Of Broccoli', 17.48, 755);
insert into products (name, price, stock) values ('Yoplait Drink', 16.83, 617);
insert into products (name, price, stock) values ('Salt - Kosher', 4.43, 607);
insert into products (name, price, stock) values ('Potatoes - Peeled', 17.64, 896);
insert into products (name, price, stock) values ('Cake - French Pear Tart', 5.58, 853);
insert into products (name, price, stock) values ('Shrimp - Black Tiger 16/20', 14.29, 532);
insert into products (name, price, stock) values ('Shrimp - 150 - 250', 9.64, 909);
insert into products (name, price, stock) values ('Butter - Salted, Micro', 3.81, 584);
insert into products (name, price, stock) values ('Onions Granulated', 11.3, 896);
insert into products (name, price, stock) values ('Aspic - Amber', 14.75, 543);
insert into products (name, price, stock) values ('Pepper - Chipotle, Canned', 15.79, 990);
insert into products (name, price, stock) values ('Kiwano', 5.37, 824);
insert into products (name, price, stock) values ('Soup - Campbells Broccoli', 18.24, 665);
insert into products (name, price, stock) values ('Extract Vanilla Pure', 12.02, 599);
insert into products (name, price, stock) values ('Transfer Sheets', 17.83, 788);
insert into products (name, price, stock) values ('Sugar - Cubes', 4.59, 710);
insert into products (name, price, stock) values ('Bread - Italian Corn Meal Poly', 12.97, 775);
insert into products (name, price, stock) values ('Meldea Green Tea Liquor', 1.47, 662);
insert into products (name, price, stock) values ('Plasticknivesblack', 4.06, 831);
insert into products (name, price, stock) values ('Carbonated Water - Blackcherry', 8.92, 538);
insert into products (name, price, stock) values ('Wine - Montecillo Rioja Crianza', 11.59, 674);
insert into products (name, price, stock) values ('Bar Mix - Pina Colada, 355 Ml', 5.97, 520);
insert into products (name, price, stock) values ('Chutney Sauce', 9.52, 730);
insert into products (name, price, stock) values ('Flower - Commercial Spider', 19.7, 959);
insert into products (name, price, stock) values ('Flour - Teff', 17.89, 782);
insert into products (name, price, stock) values ('Sherbet - Raspberry', 15.5, 933);
insert into products (name, price, stock) values ('Veal - Kidney', 13.93, 740);
insert into products (name, price, stock) values ('Tomato - Plum With Basil', 6.44, 870);
insert into products (name, price, stock) values ('Appetizer - Seafood Assortment', 14.52, 581);
insert into products (name, price, stock) values ('Marzipan 50/50', 19.62, 835);
insert into products (name, price, stock) values ('Praline Paste', 12.88, 889);
insert into products (name, price, stock) values ('Tea - Herbal Sweet Dreams', 16.69, 825);
insert into products (name, price, stock) values ('Scallops - 20/30', 12.94, 834);
insert into products (name, price, stock) values ('Syrup - Monin - Granny Smith', 5.94, 843);
insert into products (name, price, stock) values ('Bagel - Ched Chs Presliced', 1.73, 793);
insert into products (name, price, stock) values ('Juice - Mango', 3.72, 972);
insert into products (name, price, stock) values ('Wine - Sake', 9.33, 564);
insert into products (name, price, stock) values ('Juice - Orangina', 10.59, 726);
insert into products (name, price, stock) values ('Salmon Atl.whole 8 - 10 Lb', 11.21, 797);
insert into products (name, price, stock) values ('Coffee Cup 12oz 5342cd', 8.74, 594);
insert into products (name, price, stock) values ('Pasta - Fusili Tri - Coloured', 10.5, 821);
insert into products (name, price, stock) values ('Extract Vanilla Pure', 7.42, 557);
insert into products (name, price, stock) values ('Lotus Leaves', 17.42, 531);
insert into products (name, price, stock) values ('Wine - Ruffino Chianti Classico', 6.47, 564);
insert into products (name, price, stock) values ('Lettuce - Baby Salad Greens', 13.94, 772);
insert into products (name, price, stock) values ('Rum - Spiced, Captain Morgan', 13.92, 729);
insert into products (name, price, stock) values ('Water, Tap', 13.04, 764);
insert into products (name, price, stock) values ('Chocolate Eclairs', 11.55, 857);
insert into products (name, price, stock) values ('Bagel - Sesame Seed Presliced', 17.1, 548);
insert into products (name, price, stock) values ('Roe - Lump Fish, Red', 16.4, 732);
insert into products (name, price, stock) values ('Chicken - Whole Roasting', 16.12, 647);
insert into products (name, price, stock) values ('Soup - Campbells, Minestrone', 11.28, 803);
insert into products (name, price, stock) values ('Urban Zen Drinks', 7.34, 773);
insert into products (name, price, stock) values ('Wine - Casillero Del Diablo', 8.95, 984);
insert into products (name, price, stock) values ('Cookie Double Choco', 3.4, 950);
insert into products (name, price, stock) values ('Jolt Cola - Red Eye', 10.2, 793);
insert into products (name, price, stock) values ('Shrimp - Black Tiger 8 - 12', 8.41, 943);
insert into products (name, price, stock) values ('Oil - Grapeseed Oil', 19.88, 723);
insert into products (name, price, stock) values ('Fondant - Icing', 10.86, 787);
insert into products (name, price, stock) values ('Split Peas - Yellow, Dry', 10.48, 935);
insert into products (name, price, stock) values ('Ranchero - Primerba, Paste', 7.19, 577);
insert into products (name, price, stock) values ('Grapes - Green', 13.87, 508);
insert into products (name, price, stock) values ('Wine - Sawmill Creek Autumn', 3.79, 574);
insert into products (name, price, stock) values ('Table Cloth 120 Round White', 5.1, 941);
insert into products (name, price, stock) values ('Marjoram - Fresh', 14.16, 612);
insert into products (name, price, stock) values ('Ham - Cooked', 17.38, 925);
insert into products (name, price, stock) values ('Sausage - Breakfast', 6.62, 696);
insert into products (name, price, stock) values ('Chutney Sauce - Mango', 13.23, 884);
insert into products (name, price, stock) values ('Beef - Striploin Aa', 8.02, 893);
insert into products (name, price, stock) values ('Watercress', 14.34, 819);
insert into products (name, price, stock) values ('Wine - Magnotta, Merlot Sr Vqa', 12.56, 768);
insert into products (name, price, stock) values ('Lettuce - Spring Mix', 13.84, 965);
insert into products (name, price, stock) values ('Cup - 8oz Coffee Perforated', 16.42, 986);
insert into products (name, price, stock) values ('Wiberg Cure', 7.58, 900);
insert into products (name, price, stock) values ('Beef Cheek Fresh', 15.18, 640);
insert into products (name, price, stock) values ('Bread Roll Foccacia', 8.39, 723);
insert into products (name, price, stock) values ('Cheese - Provolone', 14.45, 892);
insert into products (name, price, stock) values ('Pasta - Rotini, Dry', 11.09, 506);
insert into products (name, price, stock) values ('Pepperoni Slices', 18.12, 997);
insert into products (name, price, stock) values ('Garbage Bag - Clear', 12.67, 768);
insert into products (name, price, stock) values ('Fudge - Chocolate Fudge', 13.46, 668);
insert into products (name, price, stock) values ('Turkey - Breast, Boneless Sk On', 12.37, 893);
insert into products (name, price, stock) values ('Cake - Sheet Strawberry', 6.59, 935);
insert into products (name, price, stock) values ('Container Clear 8 Oz', 19.86, 927);
insert into products (name, price, stock) values ('Gingerale - Diet - Schweppes', 19.18, 647);
insert into products (name, price, stock) values ('Wine - Redchard Merritt', 4.27, 920);
insert into products (name, price, stock) values ('Anchovy Fillets', 19.34, 778);
insert into products (name, price, stock) values ('Raisin - Dark', 11.99, 834);
insert into products (name, price, stock) values ('Pork Salted Bellies', 15.78, 794);
insert into products (name, price, stock) values ('Irish Cream - Butterscotch', 17.51, 505);
insert into products (name, price, stock) values ('Oil - Peanut', 16.79, 529);
insert into products (name, price, stock) values ('Nut - Hazelnut, Ground, Natural', 9.5, 580);
insert into products (name, price, stock) values ('Potatoes - Mini White 3 Oz', 18.33, 780);
insert into products (name, price, stock) values ('Okra', 3.85, 662);
insert into products (name, price, stock) values ('Chocolate - Milk, Callets', 13.53, 837);
insert into products (name, price, stock) values ('Soup - Campbells - Chicken Noodle', 2.42, 682);
insert into products (name, price, stock) values ('Bread - Assorted Rolls', 9.09, 660);
insert into products (name, price, stock) values ('Duck - Breast', 7.62, 777);
insert into products (name, price, stock) values ('Chocolate Bar - Coffee Crisp', 14.19, 991);
insert into products (name, price, stock) values ('General Purpose Trigger', 16.19, 770);
insert into products (name, price, stock) values ('Kellogs Raisan Bran Bars', 14.49, 501);
insert into products (name, price, stock) values ('Pork - Liver', 17.75, 986);
insert into products (name, price, stock) values ('Boogies', 10.24, 830);
insert into products (name, price, stock) values ('Wine - Wyndham Estate Bin 777', 18.64, 753);
insert into products (name, price, stock) values ('Muffin Mix - Morning Glory', 16.31, 770);
insert into products (name, price, stock) values ('Mountain Dew', 7.97, 646);
insert into products (name, price, stock) values ('Raspberries - Fresh', 19.77, 752);
insert into products (name, price, stock) values ('Jolt Cola', 18.68, 545);
insert into products (name, price, stock) values ('Pepper - White, Ground', 8.81, 531);
insert into products (name, price, stock) values ('Long Island Ice Tea', 1.15, 909);
insert into products (name, price, stock) values ('Radish', 11.11, 762);
insert into products (name, price, stock) values ('Couscous', 18.64, 600);
insert into products (name, price, stock) values ('Bread Roll Foccacia', 18.36, 554);
insert into products (name, price, stock) values ('Salmon Atl.whole 8 - 10 Lb', 9.74, 587);
insert into products (name, price, stock) values ('Compound - Raspberry', 15.08, 937);
insert into products (name, price, stock) values ('Glucose', 14.29, 536);
insert into products (name, price, stock) values ('Island Oasis - Sweet And Sour Mix', 1.23, 635);
insert into products (name, price, stock) values ('Iced Tea Concentrate', 17.61, 900);
insert into products (name, price, stock) values ('Tandoori Curry Paste', 9.32, 667);
insert into products (name, price, stock) values ('Chick Peas - Dried', 16.71, 854);
insert into products (name, price, stock) values ('Cream Of Tartar', 17.13, 674);
insert into products (name, price, stock) values ('Wine - White, Gewurtzraminer', 17.16, 653);
insert into products (name, price, stock) values ('Coffee - Decafenated', 5.94, 789);
insert into products (name, price, stock) values ('Bandage - Fexible 1x3', 11.76, 804);
insert into products (name, price, stock) values ('Orange Roughy 4/6 Oz', 11.65, 553);
insert into products (name, price, stock) values ('Chutney Sauce', 5.9, 945);
insert into products (name, price, stock) values ('Apricots - Halves', 11.03, 932);
insert into products (name, price, stock) values ('Coconut - Shredded, Unsweet', 8.82, 673);
insert into products (name, price, stock) values ('Wine - Hardys Bankside Shiraz', 12.09, 787);
insert into products (name, price, stock) values ('Sesame Seed Black', 1.72, 709);
insert into products (name, price, stock) values ('Table Cloth 53x69 White', 6.62, 864);
insert into products (name, price, stock) values ('Tomato - Plum With Basil', 19.0, 540);
insert into products (name, price, stock) values ('Kippers - Smoked', 18.04, 918);
insert into products (name, price, stock) values ('Nori Sea Weed', 12.18, 935);
insert into products (name, price, stock) values ('Croissants Thaw And Serve', 5.63, 908);
insert into products (name, price, stock) values ('Beer - Steamwhistle', 18.75, 544);
insert into products (name, price, stock) values ('Drambuie', 6.87, 639);
insert into products (name, price, stock) values ('Beets - Pickled', 10.33, 967);
insert into products (name, price, stock) values ('Wood Chips - Regular', 18.77, 1000);
insert into products (name, price, stock) values ('Barramundi', 4.5, 735);
insert into products (name, price, stock) values ('Syrup - Monin - Granny Smith', 15.41, 578);
insert into products (name, price, stock) values ('Huck Towels White', 9.93, 706);
insert into products (name, price, stock) values ('Cleaner - Lime Away', 6.8, 817);
insert into products (name, price, stock) values ('Schnappes - Peach, Walkers', 9.44, 835);
insert into products (name, price, stock) values ('Pepper - White, Whole', 7.69, 992);
insert into products (name, price, stock) values ('Sole - Fillet', 18.83, 652);
insert into products (name, price, stock) values ('Wine - Pinot Noir Mondavi Coastal', 5.52, 652);
insert into products (name, price, stock) values ('Wine - Soave Folonari', 1.95, 749);
insert into products (name, price, stock) values ('Juice - Clam, 46 Oz', 6.89, 761);
insert into products (name, price, stock) values ('Sparkling Wine - Rose, Freixenet', 6.93, 870);
insert into products (name, price, stock) values ('Beef - Salted', 16.0, 945);
insert into products (name, price, stock) values ('Foam Tray S2', 18.6, 746);
insert into products (name, price, stock) values ('Myers Planters Punch', 9.62, 788);
insert into products (name, price, stock) values ('Shortbread - Cookie Crumbs', 13.77, 519);
insert into products (name, price, stock) values ('Mushroom - Portebello', 11.08, 837);
insert into products (name, price, stock) values ('Sausage - Liver', 1.96, 510);
insert into products (name, price, stock) values ('Squash - Guords', 6.82, 837);
insert into products (name, price, stock) values ('Ecolab - Power Fusion', 16.12, 518);
insert into products (name, price, stock) values ('Wine - Ej Gallo Sonoma', 13.85, 847);
insert into products (name, price, stock) values ('Flower - Leather Leaf Fern', 8.34, 946);
insert into products (name, price, stock) values ('Yoghurt Tubes', 17.7, 519);
insert into products (name, price, stock) values ('Onions - Green', 6.02, 878);
insert into products (name, price, stock) values ('Salt - Rock, Course', 15.83, 735);
insert into products (name, price, stock) values ('Mints - Striped Red', 4.0, 776);
insert into products (name, price, stock) values ('Rabbit - Legs', 17.94, 523);
insert into products (name, price, stock) values ('Tea - Herbal - 6 Asst', 3.36, 748);
insert into products (name, price, stock) values ('Tray - 12in Rnd Blk', 6.99, 565);
insert into products (name, price, stock) values ('Taro Leaves', 19.92, 586);
insert into products (name, price, stock) values ('Pork Loin Bine - In Frenched', 16.84, 774);
insert into products (name, price, stock) values ('Yoplait Drink', 14.67, 805);
insert into products (name, price, stock) values ('Cheese - Le Cheve Noir', 6.04, 704);
insert into products (name, price, stock) values ('Parasol Pick Stir Stick', 6.62, 925);
insert into products (name, price, stock) values ('Latex Rubber Gloves Size 9', 13.84, 560);
insert into products (name, price, stock) values ('Creme De Banane - Marie', 12.61, 504);
insert into products (name, price, stock) values ('Chocolate - Milk', 6.96, 598);
insert into products (name, price, stock) values ('Veal - Bones', 17.04, 624);
insert into products (name, price, stock) values ('Vinegar - Raspberry', 19.28, 751);
insert into products (name, price, stock) values ('Taro Leaves', 18.42, 980);
insert into products (name, price, stock) values ('Strawberries - California', 11.09, 558);
insert into products (name, price, stock) values ('Soup - Campbells Mac N Cheese', 17.15, 862);
insert into products (name, price, stock) values ('Muffin Hinge 117n', 4.09, 924);
insert into products (name, price, stock) values ('Yeast Dry - Fermipan', 12.16, 630);
insert into products (name, price, stock) values ('Peach - Fresh', 10.05, 793);
insert into products (name, price, stock) values ('Beer - Maudite', 19.75, 974);
insert into products (name, price, stock) values ('Strawberries', 14.7, 780);
insert into products (name, price, stock) values ('Honey - Liquid', 5.23, 872);
insert into products (name, price, stock) values ('Chestnuts - Whole,canned', 15.44, 611);
insert into products (name, price, stock) values ('Clementine', 7.53, 860);
insert into products (name, price, stock) values ('Olives - Morracan Dired', 12.09, 741);
insert into products (name, price, stock) values ('Energy Drink - Franks Pineapple', 5.68, 957);
insert into products (name, price, stock) values ('Paper Towel Touchless', 11.8, 670);
insert into products (name, price, stock) values ('Soup - Campbells, Creamy', 17.82, 756);
insert into products (name, price, stock) values ('Chervil - Fresh', 6.82, 574);
insert into products (name, price, stock) values ('Mushrooms - Black, Dried', 18.2, 889);
insert into products (name, price, stock) values ('French Pastries', 4.02, 842);
insert into products (name, price, stock) values ('Wine - White, Ej', 10.41, 988);
insert into products (name, price, stock) values ('Toamtoes 6x7 Select', 15.48, 876);
insert into products (name, price, stock) values ('Bread Sour Rolls', 3.04, 667);
insert into products (name, price, stock) values ('Onions - Cooking', 12.1, 697);
insert into products (name, price, stock) values ('Sesame Seed Black', 13.88, 690);
insert into products (name, price, stock) values ('Shiratamako - Rice Flour', 1.05, 925);
insert into products (name, price, stock) values ('Tray - 12in Rnd Blk', 2.26, 699);
insert into products (name, price, stock) values ('Sauce - Black Current, Dry Mix', 13.95, 959);
insert into products (name, price, stock) values ('Langers - Mango Nectar', 10.39, 866);
insert into products (name, price, stock) values ('Chicken - Soup Base', 6.56, 704);
insert into products (name, price, stock) values ('Danishes - Mini Raspberry', 3.55, 639);
insert into products (name, price, stock) values ('Oregano - Dry, Rubbed', 9.53, 642);
insert into products (name, price, stock) values ('Paper - Brown Paper Mini Cups', 1.51, 834);
insert into products (name, price, stock) values ('Icecream - Dstk Cml And Fdg', 15.37, 500);
insert into products (name, price, stock) values ('Tamarind Paste', 18.34, 565);
insert into products (name, price, stock) values ('Napkin Colour', 18.44, 557);
insert into products (name, price, stock) values ('Dooleys Toffee', 13.76, 697);
insert into products (name, price, stock) values ('Spic And Span All Purpose', 9.47, 873);
insert into products (name, price, stock) values ('Sugar - Crumb', 10.52, 770);
insert into products (name, price, stock) values ('Otomegusa Dashi Konbu', 16.03, 892);
insert into products (name, price, stock) values ('Lamb - Leg, Diced', 10.11, 539);
insert into products (name, price, stock) values ('Grapes - Green', 18.21, 814);
insert into products (name, price, stock) values ('Sansho Powder', 4.68, 918);
insert into products (name, price, stock) values ('Wakami Seaweed', 4.88, 681);
insert into products (name, price, stock) values ('Juice - Happy Planet', 9.54, 779);
insert into products (name, price, stock) values ('Stock - Beef, Brown', 1.39, 899);
insert into products (name, price, stock) values ('Water - Spring 1.5lit', 7.45, 971);
insert into products (name, price, stock) values ('Chocolate - Sugar Free Semi Choc', 5.29, 663);
insert into products (name, price, stock) values ('Wine - Taylors Reserve', 13.31, 958);
insert into products (name, price, stock) values ('Wine - Periguita Fonseca', 9.1, 925);
insert into products (name, price, stock) values ('Longos - Chicken Cordon Bleu', 5.18, 998);
insert into products (name, price, stock) values ('Bread - Pumpernickle, Rounds', 2.62, 873);
insert into products (name, price, stock) values ('Sprite - 355 Ml', 2.42, 500);
insert into products (name, price, stock) values ('Wine - Red, Harrow Estates, Cab', 11.94, 743);
insert into products (name, price, stock) values ('Soup - French Can Pea', 2.3, 859);
insert into products (name, price, stock) values ('Cheese - Brie, Triple Creme', 1.73, 974);
insert into products (name, price, stock) values ('Sage - Fresh', 11.29, 581);
insert into products (name, price, stock) values ('Wine - Red, Concha Y Toro', 19.74, 535);
insert into products (name, price, stock) values ('Wine - Cotes Du Rhone', 8.96, 880);
insert into products (name, price, stock) values ('Pork - Ground', 11.18, 731);
insert into products (name, price, stock) values ('Skirt - 24 Foot', 8.01, 721);
insert into products (name, price, stock) values ('Tabasco Sauce, 2 Oz', 17.17, 940);
insert into products (name, price, stock) values ('Wine - Marlbourough Sauv Blanc', 4.55, 875);
insert into products (name, price, stock) values ('Syrup - Monin, Irish Cream', 7.88, 599);
insert into products (name, price, stock) values ('Soup - Knorr, Chicken Noodle', 8.63, 960);
insert into products (name, price, stock) values ('Pears - Bosc', 5.94, 968);
insert into products (name, price, stock) values ('Nori Sea Weed - Gold Label', 10.49, 515);
insert into products (name, price, stock) values ('Pork - Back Ribs', 4.0, 730);
insert into products (name, price, stock) values ('Eel - Smoked', 4.97, 928);
insert into products (name, price, stock) values ('Wine - Dubouef Macon - Villages', 10.35, 827);
insert into products (name, price, stock) values ('Carbonated Water - Blackberry', 7.39, 789);
insert into products (name, price, stock) values ('Paste - Black Olive', 10.43, 930);
insert into products (name, price, stock) values ('Crackers - Graham', 16.53, 937);
insert into products (name, price, stock) values ('Allspice - Jamaican', 13.63, 553);
insert into products (name, price, stock) values ('Pepsi - 600ml', 7.22, 986);
insert into products (name, price, stock) values ('Cheese - Sheep Milk', 13.25, 898);
insert into products (name, price, stock) values ('Soup - Beef, Base Mix', 2.21, 550);
insert into products (name, price, stock) values ('Lamb - Loin Chops', 7.23, 849);
insert into products (name, price, stock) values ('Chicken - Whole Roasting', 8.1, 860);
insert into products (name, price, stock) values ('Gelatine Leaves - Envelopes', 6.35, 512);
insert into products (name, price, stock) values ('Jerusalem Artichoke', 1.85, 601);
insert into products (name, price, stock) values ('Chick Peas - Dried', 18.4, 724);
insert into products (name, price, stock) values ('Artichokes - Jerusalem', 5.79, 978);
insert into products (name, price, stock) values ('Pork - Loin, Center Cut', 5.88, 912);
insert into products (name, price, stock) values ('Juice - Apple, 1.36l', 5.59, 831);
insert into products (name, price, stock) values ('Truffle Cups - White Paper', 11.32, 549);
insert into products (name, price, stock) values ('Rolled Oats', 2.08, 737);
insert into products (name, price, stock) values ('Beef - Outside, Round', 12.04, 725);
insert into products (name, price, stock) values ('Chicken - Soup Base', 11.94, 602);
insert into products (name, price, stock) values ('Bread - English Muffin', 17.63, 889);
insert into products (name, price, stock) values ('Cheese - Cheddarsliced', 1.04, 983);
insert into products (name, price, stock) values ('Table Cloth 62x114 White', 6.4, 601);
insert into products (name, price, stock) values ('Tart - Pecan Butter Squares', 17.67, 730);
insert into products (name, price, stock) values ('Table Cloth 54x72 Colour', 5.65, 826);
insert into products (name, price, stock) values ('Cardamon Seed / Pod', 13.76, 629);
insert into products (name, price, stock) values ('Arizona - Green Tea', 7.49, 653);
insert into products (name, price, stock) values ('Ecolab - Ster Bac', 2.18, 786);
insert into products (name, price, stock) values ('Salmon - Atlantic, Skin On', 3.37, 789);
insert into products (name, price, stock) values ('Fruit Mix - Light', 17.47, 757);
insert into products (name, price, stock) values ('Bread Foccacia Whole', 7.01, 500);
insert into products (name, price, stock) values ('Muffin Mix - Corn Harvest', 19.82, 673);
insert into products (name, price, stock) values ('Seaweed Green Sheets', 12.65, 978);
insert into products (name, price, stock) values ('Coconut - Shredded, Sweet', 6.15, 770);
insert into products (name, price, stock) values ('Pasta - Spaghetti, Dry', 8.46, 882);
insert into products (name, price, stock) values ('Bacardi Breezer - Strawberry', 8.33, 799);
insert into products (name, price, stock) values ('Currants', 18.01, 990);
insert into products (name, price, stock) values ('Chicken - White Meat, No Tender', 9.46, 650);
insert into products (name, price, stock) values ('Milk - Condensed', 16.62, 745);
insert into products (name, price, stock) values ('Oil - Sunflower', 6.72, 788);
insert into products (name, price, stock) values ('Shrimp - Black Tiger 6 - 8', 14.86, 998);
insert into products (name, price, stock) values ('Hickory Smoke, Liquid', 15.46, 870);
insert into products (name, price, stock) values ('Watercress', 15.22, 981);
insert into products (name, price, stock) values ('Beef Flat Iron Steak', 4.3, 785);
insert into products (name, price, stock) values ('Trout Rainbow Whole', 12.89, 725);
insert into products (name, price, stock) values ('Potatoes - Idaho 80 Count', 11.25, 868);
insert into products (name, price, stock) values ('Wine - Kwv Chenin Blanc South', 3.37, 971);
insert into products (name, price, stock) values ('Scrubbie - Scotchbrite Hand Pad', 10.17, 513);
insert into products (name, price, stock) values ('Beef - Ground Medium', 2.24, 739);
insert into products (name, price, stock) values ('Bread - Rolls, Corn', 5.83, 512);
insert into products (name, price, stock) values ('Lamb - Whole, Fresh', 16.97, 781);
insert into products (name, price, stock) values ('Wine - Lou Black Shiraz', 3.0, 560);
insert into products (name, price, stock) values ('Tuna - Sushi Grade', 14.15, 836);
insert into products (name, price, stock) values ('Cheese Cloth No 100', 5.61, 706);
insert into products (name, price, stock) values ('Nantucket - Orange Mango Cktl', 12.58, 733);
insert into products (name, price, stock) values ('Pur Value', 18.82, 972);
insert into products (name, price, stock) values ('Cakes Assorted', 5.44, 780);
insert into products (name, price, stock) values ('Sprouts - Bean', 14.42, 754);
insert into products (name, price, stock) values ('Lettuce - Escarole', 6.79, 533);
insert into products (name, price, stock) values ('Capers - Ox Eye Daisy', 10.29, 989);
insert into products (name, price, stock) values ('Appetizer - Chicken Satay', 10.61, 996);
insert into products (name, price, stock) values ('Sugar - Cubes', 8.31, 745);
insert into products (name, price, stock) values ('Wine - Redchard Merritt', 7.77, 961);
insert into products (name, price, stock) values ('Muffin Batt - Blueberry Passion', 12.4, 779);
insert into products (name, price, stock) values ('Pork - Loin, Center Cut', 1.72, 844);
